# Generated by Django 2.2.4 on 2019-10-24 21:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(verbose_name='Texto do Conheça Nosso Aplicativo')),
                ('img1', models.ImageField(upload_to='img/aplicativo', verbose_name='Imagem do Aplicativo')),
                ('playstore', models.URLField(default='http://', max_length=10000, verbose_name='Link para Download do App na PlayStore')),
                ('ios', models.URLField(default='http://', max_length=10000, verbose_name='Link para Download do App na AppStore')),
            ],
            options={
                'verbose_name': 'Aplicativo',
                'verbose_name_plural': 'Aplicativo',
            },
        ),
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=30, verbose_name='Telefone para Contato')),
                ('email', models.EmailField(max_length=50, verbose_name='Email para Contato')),
                ('wpp', models.URLField(default='http://', max_length=100, verbose_name='Link para WhatsApp')),
                ('insta', models.URLField(default='http://', max_length=100, verbose_name='Link para Instagram')),
                ('face', models.URLField(default='http://', max_length=100, verbose_name='Link para Facebook')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contato',
            },
        ),
        migrations.CreateModel(
            name='Ensino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitulo', models.CharField(default='Subtítulo', max_length=100, verbose_name='Subtítulo')),
                ('desc', models.TextField(verbose_name='Descrição da seção')),
            ],
            options={
                'verbose_name': 'Ensino',
                'verbose_name_plural': 'Ensino',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Próximo Evento', max_length=50, verbose_name='Título do evento')),
                ('img4', models.ImageField(upload_to='img/evento', verbose_name='Imagem do evento')),
                ('desc', models.TextField(verbose_name='Descrição do evento')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Evento',
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Imagem', max_length=30, verbose_name='Título da imagem')),
                ('img2', models.ImageField(upload_to='img/galeria', verbose_name='Imagem para galeria')),
            ],
            options={
                'verbose_name': 'Imagem da galeria',
                'verbose_name_plural': 'Imagens da galeria',
            },
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Projeto', max_length=100, unique=True, verbose_name='Titulo do Projeto')),
                ('atalho', models.SlugField(default='Nome-do-Projeto', max_length=100, unique=True, verbose_name='Atalho')),
                ('desc', models.TextField(default='Descrição do projeto', verbose_name='Descrição rápida do projeto')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Conteúdo do Post do Projeto')),
                ('start_date', models.DateField(auto_now=True, verbose_name='Data de criação do Post')),
                ('img_ic', models.ImageField(upload_to='img/projeto/icone', verbose_name='Imagem ícone do projeto')),
                ('img_bn', models.ImageField(upload_to='img/projeto/banner', verbose_name='Imagem banner do projeto')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
        migrations.CreateModel(
            name='PropostaPedagogica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(verbose_name='Texto da Proposta Pedagócia')),
                ('img3', models.ImageField(upload_to='img/proposta_pedagógica', verbose_name='Imagem da Proposta Pedagógica')),
            ],
            options={
                'verbose_name': 'Proposta Pedagógia',
                'verbose_name_plural': 'Proposta Pedagógica',
            },
        ),
        migrations.CreateModel(
            name='Valores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, verbose_name='Título do valor')),
            ],
            options={
                'verbose_name': 'Valor',
                'verbose_name_plural': 'Valores',
            },
        ),
    ]
