# Generated by Django 2.2.4 on 2019-10-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(verbose_name='Texto do Conheça Nosso Aplicativo')),
            ],
            options={
                'verbose_name': 'Aplicativo',
                'verbose_name_plural': 'Aplicativo',
            },
        ),
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=30, verbose_name='Telefone para Contato')),
                ('email', models.CharField(max_length=50, verbose_name='Email para Contato')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contato',
            },
        ),
        migrations.CreateModel(
            name='Ensino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Ensino', max_length=100, verbose_name='Título')),
                ('sub_tit', models.CharField(default='Conheça o método de ensino que usamos :', max_length=100, verbose_name='Subtítulo')),
                ('desc', models.TextField(default='Descrição da seção', verbose_name='Descrição da seção')),
            ],
            options={
                'verbose_name': 'Ensino',
                'verbose_name_plural': 'Ensino',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Próximo Evento', max_length=50, verbose_name='Título do evento')),
                ('desc', models.TextField(default='Descrição do Evento', verbose_name='Descrição do evento')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Evento',
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Imagem', max_length=30, verbose_name='Título da imagem')),
                ('img', models.ImageField(upload_to='', verbose_name='Imagem da galeria')),
            ],
            options={
                'verbose_name': 'Imagem da galeria',
                'verbose_name_plural': 'Imagens da galeria',
            },
        ),
        migrations.CreateModel(
            name='PropostaPedagogica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(verbose_name='Texto da Proposta Pedagócia')),
            ],
            options={
                'verbose_name': 'Proposta Pedagógia',
                'verbose_name_plural': 'Proposta Pedagógica',
            },
        ),
    ]
