# Generated by Django 2.2.4 on 2019-10-24 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aplicativo',
            old_name='img1',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='img4',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='galeria',
            old_name='img2',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='propostapedagogica',
            old_name='img3',
            new_name='img',
        ),
    ]
