# Generated by Django 2.2.4 on 2019-10-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_valores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ensino',
            name='sub_tit',
        ),
        migrations.RemoveField(
            model_name='ensino',
            name='titulo',
        ),
        migrations.AddField(
            model_name='ensino',
            name='subtitulo',
            field=models.CharField(default='Subtítulo', max_length=100, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='contatos',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email para Contato'),
        ),
        migrations.AlterField(
            model_name='valores',
            name='titulo',
            field=models.CharField(max_length=30, verbose_name='Título do valor'),
        ),
    ]
