# Generated by Django 2.2 on 2019-10-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191028_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='atalho',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Atalho'),
        ),
    ]
