# Generated by Django 2.2.4 on 2019-10-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191008_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensino',
            name='desc',
            field=models.TextField(verbose_name='Descrição da seção'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='desc',
            field=models.TextField(verbose_name='Descrição do evento'),
        ),
    ]
