# Generated by Django 2.2.4 on 2019-11-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191029_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='Data de criação do Post'),
        ),
    ]
