# Generated by Django 2.2.4 on 2019-10-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191008_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatos',
            name='face',
            field=models.URLField(default='http://', max_length=100, verbose_name='Link para Facebook'),
        ),
        migrations.AddField(
            model_name='contatos',
            name='insta',
            field=models.URLField(default='http://', max_length=100, verbose_name='Link para Instagram'),
        ),
        migrations.AddField(
            model_name='contatos',
            name='wpp',
            field=models.URLField(default='http://', max_length=100, verbose_name='Link para WhatsApp'),
        ),
    ]
