# Generated by Django 2.2.4 on 2019-10-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191012_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Projeto', max_length=100, unique=True, verbose_name='Titulo do Projeto')),
                ('alguma_coisa', models.SlugField(default='', max_length=100, verbose_name='')),
                ('content', models.TextField(verbose_name='Conteúdo do Post')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projeto',
            },
        ),
    ]
