# Generated by Django 2.2.4 on 2019-11-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191102_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='desc',
            field=models.TextField(max_length=483, verbose_name='Descrição do evento'),
        ),
    ]
