# Generated by Django 2.2.4 on 2019-10-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_projetos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensino',
            name='desc',
            field=models.TextField(max_length=10, verbose_name='Descrição da seção'),
        ),
    ]
