# Generated by Django 2.2.4 on 2019-10-13 14:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191012_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetos',
            name='alguma_coisa',
        ),
        migrations.AddField(
            model_name='projetos',
            name='atalho',
            field=models.SlugField(default='Nome-do-Projeto', max_length=100, unique=True, verbose_name='Atalho'),
        ),
        migrations.AddField(
            model_name='projetos',
            name='desc',
            field=models.TextField(default='Descrição do projeto', verbose_name='Descrição rápida do projeto'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Conteúdo do Post'),
        ),
    ]
